### ISSUE TITLE
UnhandledPromiseRejectionWarning: AggregateError TimeoutError

### ISSUE THREAD

**Issue by Super-Chama** [XeroAPI/xero-node-oauth2-app#40]
Hey all,

Couple weeks back i began experimenting with this app to learn the xero sdk and it worked a treat. But since last week i'm getting these errors whenever i run the app. I initially thought I've messed up something, so today i tried running a fresh copy from here. Unfortunately even that failed.
This error is quite persistent and would not let me authenticate with xero. but sometimes authentication does happen and everything works thereafter.

Node - v12.16.1
NPM - 6.13.4
OS - Mint 18

`(node:6088) UnhandledPromiseRejectionWarning: AggregateError: 
    TimeoutError: Timeout awaiting 'request' for 2500ms
        at ClientRequest.<anonymous> (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/request-as-event-emitter.js:176:14)
        at ClientRequest.origin.emit (/home/chamara/Development/xero-node-oauth2/node_modules/@szmarczak/http-timer/source/index.js:37:11)
        at Immediate.timeoutHandler (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/utils/timed-out.js:63:11)
    TimeoutError: Timeout awaiting 'request' for 2500ms
        at ClientRequest.<anonymous> (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/request-as-event-emitter.js:176:14)
        at ClientRequest.origin.emit (/home/chamara/Development/xero-node-oauth2/node_modules/@szmarczak/http-timer/source/index.js:37:11)
        at Immediate.timeoutHandler (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/utils/timed-out.js:63:11)
    at rejected (/home/chamara/Development/xero-node-oauth2/node_modules/p-some/index.js:71:11)
    at /home/chamara/Development/xero-node-oauth2/node_modules/p-some/index.js:85:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by SerKnight** [comment]
Hi @Super-Chama - closing this due to unable to replicate.. It looks like its maybe an issue with your environment or the versions of request that are being run.. If you can replicate it in a way that I can test, please re-open the issue.
